//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Database.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Database.Queries.SQLite", typeof(SQLite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;PermissionReportDetails&quot; (
        ///	[Id] INTEGER PRIMARY KEY, 
        ///	[PermissionReportId] int NOT NULL, 
        ///	[AccountName] nvarchar, 
        ///	[FirstName] nvarchar, 
        ///	[LastName] nvarchar, 
        ///	[Email] nvarchar, 
        ///	[Department] nvarchar,
        ///	[Division] nvarchar,
        ///	[Domain] nvarchar, 
        ///	[OriginatingGroup] nvarchar, 
        ///	[Permissions] nvarchar, 
        ///	FOREIGN KEY (PermissionReportId) REFERENCES &quot;PermissionReports&quot;(Id) ON DELETE CASCADE).
        /// </summary>
        internal static string PermissionReportDetails {
            get {
                return ResourceManager.GetString("PermissionReportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;PermissionReports&quot; (
        ///	[Id] INTEGER PRIMARY KEY, 
        ///	[User] nvarchar NOT NULL, 
        ///	[Description] nvarchar, 
        ///	[Date] datetime NOT NULL, 
        ///	[Folder] nvarchar NOT NULL, 
        ///	[Encrypted] bit NOT NULL
        ///).
        /// </summary>
        internal static string PermissionReports {
            get {
                return ResourceManager.GetString("PermissionReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;UserPermissionReportDetails&quot; (
        ///	[Id] INTEGER PRIMARY KEY, 
        ///	[UserPermissionReportId] int NOT NULL, 
        ///	[SubFolder] nvarchar, 
        ///	[CompleteName] nvarchar, 
        ///	[OriginatingGroup] nvarchar, 
        ///	[Permissions] nvarchar, 
        ///	[Domain] nvarchar, 
        ///	FOREIGN KEY (UserPermissionReportId) REFERENCES &quot;UserPermissionReports&quot;(Id) ON DELETE CASCADE).
        /// </summary>
        internal static string UserPermissionReportDetails {
            get {
                return ResourceManager.GetString("UserPermissionReportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;UserPermissionReports&quot; (
        ///	[Id] INTEGER PRIMARY KEY, 
        ///	[User] nvarchar NOT NULL, 
        ///	[Description] nvarchar, 
        ///	[Date] datetime NOT NULL, 
        ///	[Folder] nvarchar NOT NULL, 
        ///	[ReportUser] nvarchar NOT NULL,
        ///	[Encrypted] bit NOT NULL
        ///).
        /// </summary>
        internal static string UserPermissionReports {
            get {
                return ResourceManager.GetString("UserPermissionReports", resourceCulture);
            }
        }
    }
}
