//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Database.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlServer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlServer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Database.Queries.SqlServer", typeof(SqlServer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE[PermissionReportDetails](
        ///	[Id] INTEGER IDENTITY(1, 1) NOT NULL, 
        ///	PermissionReportId int NOT NULL, 
        ///	AccountName nvarchar(max),
        ///    FirstName nvarchar(max),
        ///    LastName nvarchar(max),
        ///    Email nvarchar(max),
        ///    Department nvarchar(max),
        ///    Division nvarchar(max),
        ///    Domain nvarchar(max),
        ///    OriginatingGroup nvarchar(max),
        ///    [Permissions] nvarchar(max),
        ///	CONSTRAINT[PK_PermissionReportDetail] PRIMARY KEY([Id]), 
        ///	CONSTRAINT[FK_dbo.PermissionReportDetails_dbo.PermissionReport [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PermissionReportDetails {
            get {
                return ResourceManager.GetString("PermissionReportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [PermissionReports] (
        ///	[Id] INTEGER IDENTITY (1, 1)NOT NULL, 
        ///	[User] nvarchar(max) NOT NULL, 
        ///	[Description] nvarchar(max) NULL, 
        ///	[Date] datetime NOT NULL , 
        ///	[Folder] nvarchar(max) NOT NULL, 
        ///	[Encrypted] bit NOT NULL, 
        ///	CONSTRAINT[PK_PermissionReports] PRIMARY KEY([Id]) );.
        /// </summary>
        internal static string PermissionReports {
            get {
                return ResourceManager.GetString("PermissionReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE[UserPermissionReportDetails](
        ///    [Id] INTEGER IDENTITY(1, 1) NOT NULL, 
        ///    UserPermissionReportId int NOT NULL, 
        ///    SubFolder nvarchar(max),
        ///    CompleteName nvarchar(max),
        ///    OriginatingGroup nvarchar(max),
        ///    [Permissions] nvarchar(max),
        ///    Domain nvarchar(max),
        ///	CONSTRAINT[PK_UserPermissionReportDetails] PRIMARY KEY([Id]), 
        ///	CONSTRAINT[FK_dbo.UserPermissionReportDetails_dbo.UserPermissionReports_UserPermissionReportId] 
        ///		FOREIGN KEY ([UserPermissionReportId]) REFERENCES [Use [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserPermissionReportDetails {
            get {
                return ResourceManager.GetString("UserPermissionReportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [UserPermissionReports] (
        ///	[Id] INTEGER IDENTITY (1, 1) NOT NULL, 
        ///	[User] nvarchar(max) NOT NULL, 
        ///	[Description] nvarchar(max) NULL, 
        ///	[Date] datetime NOT NULL , 
        ///	[Folder] nvarchar(max) NOT NULL, 
        ///	[ReportUser] nvarchar(max) NOT NULL,
        ///	[Encrypted] bit NOT NULL, 
        ///	CONSTRAINT[PK_UserPermissionReports] PRIMARY KEY([Id]) );.
        /// </summary>
        internal static string UserPermissionReports {
            get {
                return ResourceManager.GetString("UserPermissionReports", resourceCulture);
            }
        }
    }
}
