//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Cache Cleared..
        /// </summary>
        public static string ADCacheClearedText {
            get {
                return ResourceManager.GetString("ADCacheClearedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderSecurityViewer.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this report?.
        /// </summary>
        public static string AskRemove {
            get {
                return ResourceManager.GetString("AskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonCaption {
            get {
                return ResourceManager.GetString("CancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string CancellingTip {
            get {
                return ResourceManager.GetString("CancellingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear AD Cache and Rerun this report.
        /// </summary>
        public static string ClearADCacheAndRefreshCaption {
            get {
                return ResourceManager.GetString("ClearADCacheAndRefreshCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearButtonCaption {
            get {
                return ResourceManager.GetString("ClearButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string ClickHereLinkText {
            get {
                return ResourceManager.GetString("ClickHereLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonCaption {
            get {
                return ResourceManager.GetString("CloseButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditTip {
            get {
                return ResourceManager.GetString("EditTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderSecurityViewer - Trial Edition.
        /// </summary>
        public static string EvalAppTitle {
            get {
                return ResourceManager.GetString("EvalAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All Reports.
        /// </summary>
        public static string ExportAllCaption {
            get {
                return ResourceManager.GetString("ExportAllCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportCaption {
            get {
                return ResourceManager.GetString("ExportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportTip {
            get {
                return ResourceManager.GetString("ExportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButtonCaption {
            get {
                return ResourceManager.GetString("OKButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        public static string OrderNowText {
            get {
                return ResourceManager.GetString("OrderNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string PageFirstTip {
            get {
                return ResourceManager.GetString("PageFirstTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string PageLastTip {
            get {
                return ResourceManager.GetString("PageLastTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PageNextTip {
            get {
                return ResourceManager.GetString("PageNextTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PagePreviousTip {
            get {
                return ResourceManager.GetString("PagePreviousTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string PageSizeShowCaption {
            get {
                return ResourceManager.GetString("PageSizeShowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        public static string PaginationOfText {
            get {
                return ResourceManager.GetString("PaginationOfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerun this report..
        /// </summary>
        public static string RefreshReportTip {
            get {
                return ResourceManager.GetString("RefreshReportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveTip {
            get {
                return ResourceManager.GetString("RemoveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To compare two reports select them and open context menu.
        /// </summary>
        public static string ReportCompareText {
            get {
                return ResourceManager.GetString("ReportCompareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports are limited to {0} rows..
        /// </summary>
        public static string ResultLimitText {
            get {
                return ResourceManager.GetString("ResultLimitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rows found..
        /// </summary>
        public static string RowsFoundText {
            get {
                return ResourceManager.GetString("RowsFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonCaption {
            get {
                return ResourceManager.GetString("SaveButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButtonCaption {
            get {
                return ResourceManager.GetString("SearchButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to search.
        /// </summary>
        public static string SearchTip {
            get {
                return ResourceManager.GetString("SearchTip", resourceCulture);
            }
        }
    }
}
