//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationFolderResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationFolderResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.ConfigurationFolderResource", typeof(ConfigurationFolderResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get File Count and Size of Folder (without subfolders).
        /// </summary>
        public static string FileCountCaption {
            get {
                return ResourceManager.GetString("FileCountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get File Count and Size of Folder (including subfolders).
        /// </summary>
        public static string FileCountWithSubFolderCaption {
            get {
                return ResourceManager.GetString("FileCountWithSubFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Current Folder.
        /// </summary>
        public static string IncludeCurrentFolderCaption {
            get {
                return ResourceManager.GetString("IncludeCurrentFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Hidden Folders.
        /// </summary>
        public static string IncludeHiddenFoldersCaption {
            get {
                return ResourceManager.GetString("IncludeHiddenFoldersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Sub Folders.
        /// </summary>
        public static string IncludeSubFoldersCaption {
            get {
                return ResourceManager.GetString("IncludeSubFoldersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string OwnerCaption {
            get {
                return ResourceManager.GetString("OwnerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string ReportFolderCaption {
            get {
                return ResourceManager.GetString("ReportFolderCaption", resourceCulture);
            }
        }
    }
}
