//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.ConfigurationResource", typeof(ConfigurationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutCaption {
            get {
                return ResourceManager.GetString("AboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software to analyze the effective permissions of a Windows share or folder. &lt;LineBreak /&gt;Working PC must be a member of a Active Directory domain. &lt;LineBreak /&gt;Made by &lt;Bold&gt;&lt;Hyperlink NavigateUri=&quot;https://www.g-tac.de/Software&quot;&gt;G-TAC Software UG&lt;/Hyperlink&gt; &lt;/Bold&gt; (haftungsbeschraenkt)..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ACL.
        /// </summary>
        public static string AclGridVisibleCaption {
            get {
                return ResourceManager.GetString("AclGridVisibleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddCaption {
            get {
                return ResourceManager.GetString("AddCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Active Directory Groups.
        /// </summary>
        public static string ADGroupCaption {
            get {
                return ResourceManager.GetString("ADGroupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown Active Directory User Properties.
        /// </summary>
        public static string ADPropertiesCaption {
            get {
                return ResourceManager.GetString("ADPropertiesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Built-in Groups.
        /// </summary>
        public static string BuiltInGroupCaption {
            get {
                return ResourceManager.GetString("BuiltInGroupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BuiltInGroupDescriptionCaption {
            get {
                return ResourceManager.GetString("BuiltInGroupDescriptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string BuiltInGroupExcludedCaption {
            get {
                return ResourceManager.GetString("BuiltInGroupExcludedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BuiltInGroupNameCaption {
            get {
                return ResourceManager.GetString("BuiltInGroupNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdateCaption {
            get {
                return ResourceManager.GetString("CheckForUpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string CheckingForUpdatesText {
            get {
                return ResourceManager.GetString("CheckingForUpdatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear AD Cache.
        /// </summary>
        public static string CleanADCacheCaption {
            get {
                return ResourceManager.GetString("CleanADCacheCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ConfigurationCaption {
            get {
                return ResourceManager.GetString("ConfigurationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string cannot be saved. {0}.
        /// </summary>
        public static string ConnectionStringChangeError {
            get {
                return ResourceManager.GetString("ConnectionStringChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string CultureCaption {
            get {
                return ResourceManager.GetString("CultureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteCaption {
            get {
                return ResourceManager.GetString("DeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayNameCaption {
            get {
                return ResourceManager.GetString("DisplayNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditCaption {
            get {
                return ResourceManager.GetString("EditCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Permission Set.
        /// </summary>
        public static string EditTranslationCaption {
            get {
                return ResourceManager.GetString("EditTranslationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Disabled Users.
        /// </summary>
        public static string ExcludeDisabledUsers {
            get {
                return ResourceManager.GetString("ExcludeDisabledUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run FSV as Administrator to use this feature!.
        /// </summary>
        public static string ExcludeDisabledUsersDescription {
            get {
                return ResourceManager.GetString("ExcludeDisabledUsersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 results found for &apos;{0}&apos;.
        /// </summary>
        public static string ExclusionGroupNoResultText {
            get {
                return ResourceManager.GetString("ExclusionGroupNoResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search AD Group for Exclusion.
        /// </summary>
        public static string ExclusionGroupSearchTitle {
            get {
                return ResourceManager.GetString("ExclusionGroupSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupNameCaption {
            get {
                return ResourceManager.GetString("GroupNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogCaption {
            get {
                return ResourceManager.GetString("LogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Logging.
        /// </summary>
        public static string LogEnableCaption {
            get {
                return ResourceManager.GetString("LogEnableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameCaption {
            get {
                return ResourceManager.GetString("NameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string NetworkCaption {
            get {
                return ResourceManager.GetString("NetworkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom proxy settings.
        /// </summary>
        public static string NetworkCustomProxyCaption {
            get {
                return ResourceManager.GetString("NetworkCustomProxyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Proxy.
        /// </summary>
        public static string NetworkNoProxyCaption {
            get {
                return ResourceManager.GetString("NetworkNoProxyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default operating system settings.
        /// </summary>
        public static string NetworkOSProxyCaption {
            get {
                return ResourceManager.GetString("NetworkOSProxyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Server Settings.
        /// </summary>
        public static string NetworkProxyCaption {
            get {
                return ResourceManager.GetString("NetworkProxyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy server requires username and password..
        /// </summary>
        public static string NetworkProxyCredentialsRequiredCaption {
            get {
                return ResourceManager.GetString("NetworkProxyCredentialsRequiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string NetworkProxyPasswordCaption {
            get {
                return ResourceManager.GetString("NetworkProxyPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string NetworkProxyPortCaption {
            get {
                return ResourceManager.GetString("NetworkProxyPortCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string NetworkProxyServerCaption {
            get {
                return ResourceManager.GetString("NetworkProxyServerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string NetworkProxyUserNameCaption {
            get {
                return ResourceManager.GetString("NetworkProxyUserNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubleclick a row to add a group.
        /// </summary>
        public static string NewGroupDescription {
            get {
                return ResourceManager.GetString("NewGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder.
        /// </summary>
        public static string OpenLogFolderCaption {
            get {
                return ResourceManager.GetString("OpenLogFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in Groups.
        /// </summary>
        public static string PermissionBuiltInGroupsHeader {
            get {
                return ResourceManager.GetString("PermissionBuiltInGroupsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded AD Groups.
        /// </summary>
        public static string PermissionExclusionHeader {
            get {
                return ResourceManager.GetString("PermissionExclusionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string PermissionGeneralHeader {
            get {
                return ResourceManager.GetString("PermissionGeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown Results on Page.
        /// </summary>
        public static string PermissionPageSizeCaption {
            get {
                return ResourceManager.GetString("PermissionPageSizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Columns.
        /// </summary>
        public static string PermissionReportColumnHeader {
            get {
                return ResourceManager.GetString("PermissionReportColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string PermissionTranslationHeader {
            get {
                return ResourceManager.GetString("PermissionTranslationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportCaption {
            get {
                return ResourceManager.GetString("ReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string ReportPermissionCaption {
            get {
                return ResourceManager.GetString("ReportPermissionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permissions.
        /// </summary>
        public static string ReportUserCaption {
            get {
                return ResourceManager.GetString("ReportUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart FolderSecurityViewer for changes to take effect..
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Default Settings.
        /// </summary>
        public static string RestoreDefaultCaption {
            get {
                return ResourceManager.GetString("RestoreDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveCaption {
            get {
                return ResourceManager.GetString("SaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ScanLevelAllCaption {
            get {
                return ResourceManager.GetString("ScanLevelAllCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Depth:.
        /// </summary>
        public static string ScanLevelCaption {
            get {
                return ResourceManager.GetString("ScanLevelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Active Directory.
        /// </summary>
        public static string SearchADCaption {
            get {
                return ResourceManager.GetString("SearchADCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string SelectedCaption {
            get {
                return ResourceManager.GetString("SelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectHeaderCaption {
            get {
                return ResourceManager.GetString("SelectHeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SID.
        /// </summary>
        public static string SIDCaption {
            get {
                return ResourceManager.GetString("SIDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string TranslatedNameCaption {
            get {
                return ResourceManager.GetString("TranslatedNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Control Type.
        /// </summary>
        public static string TranslationACLCaption {
            get {
                return ResourceManager.GetString("TranslationACLCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritance.
        /// </summary>
        public static string TranslationInheritanceCaption {
            get {
                return ResourceManager.GetString("TranslationInheritanceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations for Permission Entries.
        /// </summary>
        public static string TranslationItemCaption {
            get {
                return ResourceManager.GetString("TranslationItemCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Name.
        /// </summary>
        public static string TranslationNameCaption {
            get {
                return ResourceManager.GetString("TranslationNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string TranslationPermissionsCaption {
            get {
                return ResourceManager.GetString("TranslationPermissionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete..
        /// </summary>
        public static string UpdateDownloadCompleteText {
            get {
                return ResourceManager.GetString("UpdateDownloadCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading setup file. Please check your internet connection. Error: {0}.
        /// </summary>
        public static string UpdateDownloadingError {
            get {
                return ResourceManager.GetString("UpdateDownloadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}%....
        /// </summary>
        public static string UpdateDownloadingProgressText {
            get {
                return ResourceManager.GetString("UpdateDownloadingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string UpdateDownloadingText {
            get {
                return ResourceManager.GetString("UpdateDownloadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string UpdatesCaption {
            get {
                return ResourceManager.GetString("UpdatesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderSecurityViewer is up to date..
        /// </summary>
        public static string UpdateUpToDateText {
            get {
                return ResourceManager.GetString("UpdateUpToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show User Count.
        /// </summary>
        public static string UsersCountCaption {
            get {
                return ResourceManager.GetString("UsersCountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Count at Installation: {0}.
        /// </summary>
        public static string UsersCountText {
            get {
                return ResourceManager.GetString("UsersCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users have not been counted yet..
        /// </summary>
        public static string UsersNotCountedText {
            get {
                return ResourceManager.GetString("UsersNotCountedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.{1}.{2}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
