//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to folder &quot;{0}&quot; is denied..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare because the selected folders are different..
        /// </summary>
        public static string CompareFailedDifferentFolder {
            get {
                return ResourceManager.GetString("CompareFailedDifferentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database has not been created..
        /// </summary>
        public static string DatabaseNotExist {
            get {
                return ResourceManager.GetString("DatabaseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have rights to access database..
        /// </summary>
        public static string DatabasePermissionDenied {
            get {
                return ResourceManager.GetString("DatabasePermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to database. Make sure the database is running..
        /// </summary>
        public static string DatabaseUnavailable {
            get {
                return ResourceManager.GetString("DatabaseUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        public static string DirectoryNotExist {
            get {
                return ResourceManager.GetString("DirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database has not been created..
        /// </summary>
        public static string InvalidDatabase {
            get {
                return ResourceManager.GetString("InvalidDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source you provided is not accessible..
        /// </summary>
        public static string InvalidDataSource {
            get {
                return ResourceManager.GetString("InvalidDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property name: {0}.
        /// </summary>
        public static string InvalidPropertyNameText {
            get {
                return ResourceManager.GetString("InvalidPropertyNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid template..
        /// </summary>
        public static string InvalidTemplate {
            get {
                return ResourceManager.GetString("InvalidTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You user id or password is incorrect..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed for user &apos;{0}&apos;..
        /// </summary>
        public static string LoginFailedOrDbInvalid {
            get {
                return ResourceManager.GetString("LoginFailedOrDbInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently logged-on user is local. Please log on as a domain user..
        /// </summary>
        public static string NoDomainUser {
            get {
                return ResourceManager.GetString("NoDomainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or emtpy..
        /// </summary>
        public static string NullOrEmptyError {
            get {
                return ResourceManager.GetString("NullOrEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have rights to create database..
        /// </summary>
        public static string ObjectCreationFailed {
            get {
                return ResourceManager.GetString("ObjectCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workstation is not joined to a domain or not connected to any domain..
        /// </summary>
        public static string WorkstationOutOfDomain {
            get {
                return ResourceManager.GetString("WorkstationOutOfDomain", resourceCulture);
            }
        }
    }
}
