//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.ExportResource", typeof(ExportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Control List.
        /// </summary>
        public static string ACLCaption {
            get {
                return ResourceManager.GetString("ACLCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy File to Clipboard.
        /// </summary>
        public static string CopyFileToClipboardCaption {
            get {
                return ResourceManager.GetString("CopyFileToClipboardCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy File Path to Clipboard.
        /// </summary>
        public static string CopyPathToClipboard {
            get {
                return ResourceManager.GetString("CopyPathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff. from Parent.
        /// </summary>
        public static string DiffFromParentCaption {
            get {
                return ResourceManager.GetString("DiffFromParentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As....
        /// </summary>
        public static string ExportAsCaption {
            get {
                return ResourceManager.GetString("ExportAsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while exporting a report. Please check log for more details..
        /// </summary>
        public static string ExportIOError {
            get {
                return ResourceManager.GetString("ExportIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string ExportOpenCaption {
            get {
                return ResourceManager.GetString("ExportOpenCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during opening file {0}..
        /// </summary>
        public static string ExportServiceError {
            get {
                return ResourceManager.GetString("ExportServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Report.
        /// </summary>
        public static string FolderReportCaption {
            get {
                return ResourceManager.GetString("FolderReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reports to export..
        /// </summary>
        public static string NoReportsToExportText {
            get {
                return ResourceManager.GetString("NoReportsToExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trustees.
        /// </summary>
        public static string NoTrusteesCaption {
            get {
                return ResourceManager.GetString("NoTrusteesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFileCaption {
            get {
                return ResourceManager.GetString("OpenFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Report.
        /// </summary>
        public static string OwnerReportCaption {
            get {
                return ResourceManager.GetString("OwnerReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Report.
        /// </summary>
        public static string PermissionReportCaption {
            get {
                return ResourceManager.GetString("PermissionReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string PermissionsCaption {
            get {
                return ResourceManager.GetString("PermissionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Report.
        /// </summary>
        public static string ShareReportCaption {
            get {
                return ResourceManager.GetString("ShareReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ShareReportColumnNameCaption {
            get {
                return ResourceManager.GetString("ShareReportColumnNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string ShareReportColumnPermissionCaption {
            get {
                return ResourceManager.GetString("ShareReportColumnPermissionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SidType.
        /// </summary>
        public static string ShareReportColumnSidTypeCaption {
            get {
                return ResourceManager.GetString("ShareReportColumnSidTypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WellKnownSid.
        /// </summary>
        public static string ShareReportColumnWellKnownSidCaption {
            get {
                return ResourceManager.GetString("ShareReportColumnWellKnownSidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permission Report.
        /// </summary>
        public static string UserReportCaption {
            get {
                return ResourceManager.GetString("UserReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Name.
        /// </summary>
        public static string UserReportCompareColumnNameCaption {
            get {
                return ResourceManager.GetString("UserReportCompareColumnNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Report.
        /// </summary>
        public static string UserReportCompareColumnNewReportCaption {
            get {
                return ResourceManager.GetString("UserReportCompareColumnNewReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Report.
        /// </summary>
        public static string UserReportCompareColumnOldReportCaption {
            get {
                return ResourceManager.GetString("UserReportCompareColumnOldReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string UserReportCompareColumnStateCaption {
            get {
                return ResourceManager.GetString("UserReportCompareColumnStateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string UserReportCompareColumnTextCaption {
            get {
                return ResourceManager.GetString("UserReportCompareColumnTextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped Folders.
        /// </summary>
        public static string UserReportSkippedFoldersCaption {
            get {
                return ResourceManager.GetString("UserReportSkippedFoldersCaption", resourceCulture);
            }
        }
    }
}
