//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FolderReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FolderReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.FolderReportResource", typeof(FolderReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled..
        /// </summary>
        public static string CancelledText {
            get {
                return ResourceManager.GetString("CancelledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Name.
        /// </summary>
        public static string CompleteNameCaption {
            get {
                return ResourceManager.GetString("CompleteNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportCaption {
            get {
                return ResourceManager.GetString("ExportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Count.
        /// </summary>
        public static string FileCountCaption {
            get {
                return ResourceManager.GetString("FileCountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Count Sum.
        /// </summary>
        public static string FileCountSumCaption {
            get {
                return ResourceManager.GetString("FileCountSumCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string FolderCaption {
            get {
                return ResourceManager.GetString("FolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is empty..
        /// </summary>
        public static string FolderEmptyText {
            get {
                return ResourceManager.GetString("FolderEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders found..
        /// </summary>
        public static string FolderResultsText {
            get {
                return ResourceManager.GetString("FolderResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folder found..
        /// </summary>
        public static string FolderResultText {
            get {
                return ResourceManager.GetString("FolderResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{1}&quot; - {0} folders found..
        /// </summary>
        public static string FolderSearchResultsText {
            get {
                return ResourceManager.GetString("FolderSearchResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{1}&quot; - {0} folder found..
        /// </summary>
        public static string FolderSearchResultText {
            get {
                return ResourceManager.GetString("FolderSearchResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folders found..
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string OwnerCaption {
            get {
                return ResourceManager.GetString("OwnerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string PaginationFoldersCaption {
            get {
                return ResourceManager.GetString("PaginationFoldersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Report.
        /// </summary>
        public static string ReportCaption {
            get {
                return ResourceManager.GetString("ReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareCaption {
            get {
                return ResourceManager.GetString("ShareCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SizeCaption {
            get {
                return ResourceManager.GetString("SizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Sum.
        /// </summary>
        public static string SizeSumCaption {
            get {
                return ResourceManager.GetString("SizeSumCaption", resourceCulture);
            }
        }
    }
}
