//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GroupMemberResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupMemberResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.GroupMemberResource", typeof(GroupMemberResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountNameCaption {
            get {
                return ResourceManager.GetString("AccountNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Members of {0}.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayNameCaption {
            get {
                return ResourceManager.GetString("DisplayNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string DomainCaption {
            get {
                return ResourceManager.GetString("DomainCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupText {
            get {
                return ResourceManager.GetString("GroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No members found..
        /// </summary>
        public static string ListEmptyText {
            get {
                return ResourceManager.GetString("ListEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Membership.
        /// </summary>
        public static string MembershipCaption {
            get {
                return ResourceManager.GetString("MembershipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members of {0}.
        /// </summary>
        public static string MembershipDisplayName {
            get {
                return ResourceManager.GetString("MembershipDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups found..
        /// </summary>
        public static string MembershipListEmptyText {
            get {
                return ResourceManager.GetString("MembershipListEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 group found..
        /// </summary>
        public static string MembershipOneGroupCaption {
            get {
                return ResourceManager.GetString("MembershipOneGroupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string MembershipPagesCaption {
            get {
                return ResourceManager.GetString("MembershipPagesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} groups found..
        /// </summary>
        public static string MembershipTotalGroupsCaption {
            get {
                return ResourceManager.GetString("MembershipTotalGroupsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 member found..
        /// </summary>
        public static string OneMemberCaption {
            get {
                return ResourceManager.GetString("OneMemberCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU.
        /// </summary>
        public static string OUCaption {
            get {
                return ResourceManager.GetString("OUCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string ShowMembersCaption {
            get {
                return ResourceManager.GetString("ShowMembersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} members found..
        /// </summary>
        public static string TotalMembersCaption {
            get {
                return ResourceManager.GetString("TotalMembersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeCaption {
            get {
                return ResourceManager.GetString("TypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserText {
            get {
                return ResourceManager.GetString("UserText", resourceCulture);
            }
        }
    }
}
