//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.HomeResource", typeof(HomeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select AD User.
        /// </summary>
        public static string ADBrowserCaption {
            get {
                return ResourceManager.GetString("ADBrowserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        public static string ADBrowserTreeCaption {
            get {
                return ResourceManager.GetString("ADBrowserTreeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ADBrowserTreePropertiesCaption {
            get {
                return ResourceManager.GetString("ADBrowserTreePropertiesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View active directory listing..
        /// </summary>
        public static string ADBrowserTreeText {
            get {
                return ResourceManager.GetString("ADBrowserTreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Servers.
        /// </summary>
        public static string AddServersCaption {
            get {
                return ResourceManager.GetString("AddServersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Folder.
        /// </summary>
        public static string BackCaption {
            get {
                return ResourceManager.GetString("BackCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Domain.
        /// </summary>
        public static string ChangeDomainCaption {
            get {
                return ResourceManager.GetString("ChangeDomainCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compared Permissions.
        /// </summary>
        public static string ComparedPermissionsCaption {
            get {
                return ResourceManager.GetString("ComparedPermissionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compared User Reports.
        /// </summary>
        public static string ComparedUserReportsCaption {
            get {
                return ResourceManager.GetString("ComparedUserReportsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string DirectoryCaption {
            get {
                return ResourceManager.GetString("DirectoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string DirectoryTreeCaption {
            get {
                return ResourceManager.GetString("DirectoryTreeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View folder listing..
        /// </summary>
        public static string DirectoryTreeText {
            get {
                return ResourceManager.GetString("DirectoryTreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view options..
        /// </summary>
        public static string ExportOptionsToolTip {
            get {
                return ResourceManager.GetString("ExportOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter folder path.
        /// </summary>
        public static string FolderPathPlaceholder {
            get {
                return ResourceManager.GetString("FolderPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Report.
        /// </summary>
        public static string FolderReportCaption {
            get {
                return ResourceManager.GetString("FolderReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder first to create a Folder Report..
        /// </summary>
        public static string FolderReportText {
            get {
                return ResourceManager.GetString("FolderReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Permissions Report.
        /// </summary>
        public static string GroupPermissionsReportCaption {
            get {
                return ResourceManager.GetString("GroupPermissionsReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeCaption {
            get {
                return ResourceManager.GetString("HomeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path to Clipboard.
        /// </summary>
        public static string MenuCopyPathCaption {
            get {
                return ResourceManager.GetString("MenuCopyPathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cmd.
        /// </summary>
        public static string MenuOpenCmdCaption {
            get {
                return ResourceManager.GetString("MenuOpenCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Explorer.
        /// </summary>
        public static string MenuOpenExplorerCaption {
            get {
                return ResourceManager.GetString("MenuOpenExplorerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string MenuPropertiesCaption {
            get {
                return ResourceManager.GetString("MenuPropertiesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageCaption {
            get {
                return ResourceManager.GetString("MessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextCaption {
            get {
                return ResourceManager.GetString("NextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reports started.
        /// </summary>
        public static string NoReportsText {
            get {
                return ResourceManager.GetString("NoReportsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string OpenCaption {
            get {
                return ResourceManager.GetString("OpenCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Report.
        /// </summary>
        public static string OwnerReportCaption {
            get {
                return ResourceManager.GetString("OwnerReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder from tree and user from AD browser to start owner report..
        /// </summary>
        public static string OwnerReportText {
            get {
                return ResourceManager.GetString("OwnerReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Report.
        /// </summary>
        public static string PermissionReportCaption {
            get {
                return ResourceManager.GetString("PermissionReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder from tree to start permission report..
        /// </summary>
        public static string PermissionReportText {
            get {
                return ResourceManager.GetString("PermissionReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Tree.
        /// </summary>
        public static string ReloadTreeCaption {
            get {
                return ResourceManager.GetString("ReloadTreeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove UNC Path.
        /// </summary>
        public static string RemoveUncPathCaption {
            get {
                return ResourceManager.GetString("RemoveUncPathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Here.
        /// </summary>
        public static string ReportOptionsCaption {
            get {
                return ResourceManager.GetString("ReportOptionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsCaption {
            get {
                return ResourceManager.GetString("ReportsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Template.
        /// </summary>
        public static string SaveAsTemplateCaption {
            get {
                return ResourceManager.GetString("SaveAsTemplateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Permissions.
        /// </summary>
        public static string SavedPermissionCaption {
            get {
                return ResourceManager.GetString("SavedPermissionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View a list of permission reports saved in the database..
        /// </summary>
        public static string SavedPermissionReportsText {
            get {
                return ResourceManager.GetString("SavedPermissionReportsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports and Templates in Database.
        /// </summary>
        public static string SavedReportOptionsCaption {
            get {
                return ResourceManager.GetString("SavedReportOptionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database: User Reports.
        /// </summary>
        public static string SavedUserReportCaption {
            get {
                return ResourceManager.GetString("SavedUserReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View list of user-specific permission reports saved in the database..
        /// </summary>
        public static string SavedUserReportsText {
            get {
                return ResourceManager.GetString("SavedUserReportsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search user or group before starting &apos;Owner Report&apos; or &apos;User Report&apos;..
        /// </summary>
        public static string SearchUserPrincipal {
            get {
                return ResourceManager.GetString("SearchUserPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then select one Active Directory user to start the &apos;User Permissions Report&apos;. Then click the &apos;Start&apos; button..
        /// </summary>
        public static string SelectADToolTip {
            get {
                return ResourceManager.GetString("SelectADToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder first to generate a new report. Then click the &apos;Start&apos; or &apos;Next&apos; button..
        /// </summary>
        public static string SelectFolderToolTip {
            get {
                return ResourceManager.GetString("SelectFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select server and share first to generate a new Share Report. Then click the &apos;Start&apos; button..
        /// </summary>
        public static string SelectShareServerToolTip {
            get {
                return ResourceManager.GetString("SelectShareServerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string SelectTemplatesCaption {
            get {
                return ResourceManager.GetString("SelectTemplatesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Server.
        /// </summary>
        public static string ServersCaption {
            get {
                return ResourceManager.GetString("ServersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsCaption {
            get {
                return ResourceManager.GetString("SettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Report.
        /// </summary>
        public static string ShareReportCaption {
            get {
                return ResourceManager.GetString("ShareReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/scan servers, or select from AD browser, and start share report..
        /// </summary>
        public static string ShareReportText {
            get {
                return ResourceManager.GetString("ShareReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string SplashLoadingText {
            get {
                return ResourceManager.GetString("SplashLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartCaption {
            get {
                return ResourceManager.GetString("StartCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFS Permission Report.
        /// </summary>
        public static string StartPermissionReportCaption {
            get {
                return ResourceManager.GetString("StartPermissionReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string TemplatesCaption {
            get {
                return ResourceManager.GetString("TemplatesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, edit or remove templates. or start a new report from template..
        /// </summary>
        public static string TemplatesText {
            get {
                return ResourceManager.GetString("TemplatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permission Report.
        /// </summary>
        public static string UserReportCaption {
            get {
                return ResourceManager.GetString("UserReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory from tree, and user from AD browser to start user specific permission report..
        /// </summary>
        public static string UserReportText {
            get {
                return ResourceManager.GetString("UserReportText", resourceCulture);
            }
        }
    }
}
