//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OwnerReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OwnerReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.OwnerReportResource", typeof(OwnerReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Name.
        /// </summary>
        public static string CompleteNameCaption {
            get {
                return ResourceManager.GetString("CompleteNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string FolderCaption {
            get {
                return ResourceManager.GetString("FolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{1}&apos; is owner of {0} folders..
        /// </summary>
        public static string FolderResultsText {
            get {
                return ResourceManager.GetString("FolderResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{1}&apos; is owner of {0} folder..
        /// </summary>
        public static string FolderResultText {
            get {
                return ResourceManager.GetString("FolderResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{2}&quot; - &apos;{1}&apos; is owner of {0} folders..
        /// </summary>
        public static string FolderSearchResultsText {
            get {
                return ResourceManager.GetString("FolderSearchResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{2}&quot; - &apos;{1}&apos; is owner of {0} folder..
        /// </summary>
        public static string FolderSearchResultText {
            get {
                return ResourceManager.GetString("FolderSearchResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folders found.
        /// </summary>
        public static string LoadingFoldersText {
            get {
                return ResourceManager.GetString("LoadingFoldersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder found.
        /// </summary>
        public static string LoadingFolderText {
            get {
                return ResourceManager.GetString("LoadingFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string OwnerCaption {
            get {
                return ResourceManager.GetString("OwnerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Report.
        /// </summary>
        public static string OwnerReportCaption {
            get {
                return ResourceManager.GetString("OwnerReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string PrincipalTypeCaption {
            get {
                return ResourceManager.GetString("PrincipalTypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Starting Point.
        /// </summary>
        public static string SetStartPointCaption {
            get {
                return ResourceManager.GetString("SetStartPointCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Please select valid starting point..
        /// </summary>
        public static string SetStartPointInvalidPathText {
            get {
                return ResourceManager.GetString("SetStartPointInvalidPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select starting point.
        /// </summary>
        public static string SetStartPointText {
            get {
                return ResourceManager.GetString("SetStartPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Report.
        /// </summary>
        public static string ShowOwnerReportCaption {
            get {
                return ResourceManager.GetString("ShowOwnerReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permissions Report.
        /// </summary>
        public static string ShowUserReportCaption {
            get {
                return ResourceManager.GetString("ShowUserReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users &amp; Groups.
        /// </summary>
        public static string UsersAndGroupsCaption {
            get {
                return ResourceManager.GetString("UsersAndGroupsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit enter to search or press Search button.
        ///Search is done for SamAccountName and DisplayName.
        ///You can use * as a wildcard..
        /// </summary>
        public static string UsersAndGroupToolTip {
            get {
                return ResourceManager.GetString("UsersAndGroupToolTip", resourceCulture);
            }
        }
    }
}
