//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OwnerReportTourResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OwnerReportTourResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.OwnerReportTourResource", typeof(OwnerReportTourResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click through the structure of your domain to select a user. Then double click on it to start owner report. Alternatively, you can right click, and hit {0}.
        /// </summary>
        public static string ADTree {
            get {
                return ResourceManager.GetString("ADTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can optionally write the path of mapped folder here..
        /// </summary>
        public static string FolderPathTextBox {
            get {
                return ResourceManager.GetString("FolderPathTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First expand the Folders-Tree and select a folder. Then click tab &quot;{0}&quot; above to select a user in Active Directory..
        /// </summary>
        public static string FolderTree {
            get {
                return ResourceManager.GetString("FolderTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see all results of selected folder and domain user..
        /// </summary>
        public static string ScanReport {
            get {
                return ResourceManager.GetString("ScanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to search user or view the list of members of group..
        /// </summary>
        public static string SearchPrincipal {
            get {
                return ResourceManager.GetString("SearchPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view Owner Report. Make sure to select a folder before starting the report..
        /// </summary>
        public static string ShowOwnerReport {
            get {
                return ResourceManager.GetString("ShowOwnerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name of user and click Search button. Hit enter to search or press Search button. Search is done for SamAccountName and DisplayName. You can use * as a wildcard..
        /// </summary>
        public static string UserOrGroupTextBox {
            get {
                return ResourceManager.GetString("UserOrGroupTextBox", resourceCulture);
            }
        }
    }
}
