//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionCompareResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionCompareResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.PermissionCompareResource", typeof(PermissionCompareResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountNameCaption {
            get {
                return ResourceManager.GetString("AccountNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string CompareAdded {
            get {
                return ResourceManager.GetString("CompareAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string CompareAll {
            get {
                return ResourceManager.GetString("CompareAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string CompareChanged {
            get {
                return ResourceManager.GetString("CompareChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select two reports with same folder path..
        /// </summary>
        public static string CompareDifferentReportsText {
            get {
                return ResourceManager.GetString("CompareDifferentReportsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select only two items to compare..
        /// </summary>
        public static string CompareItemsError {
            get {
                return ResourceManager.GetString("CompareItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Similar.
        /// </summary>
        public static string CompareNotSimilar {
            get {
                return ResourceManager.GetString("CompareNotSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string CompareRemoved {
            get {
                return ResourceManager.GetString("CompareRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Report.
        /// </summary>
        public static string CompareReportTitle {
            get {
                return ResourceManager.GetString("CompareReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar.
        /// </summary>
        public static string CompareSimilar {
            get {
                return ResourceManager.GetString("CompareSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Report.
        /// </summary>
        public static string NewReportCaption {
            get {
                return ResourceManager.GetString("NewReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Report.
        /// </summary>
        public static string OldReportCaption {
            get {
                return ResourceManager.GetString("OldReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string PageSizeCaption {
            get {
                return ResourceManager.GetString("PageSizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is added with these permissions: {1}..
        /// </summary>
        public static string PermissionAddedText {
            get {
                return ResourceManager.GetString("PermissionAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has got permissions changed: {1}..
        /// </summary>
        public static string PermissionChangedText {
            get {
                return ResourceManager.GetString("PermissionChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Reports of {0} and {1}.
        /// </summary>
        public static string PermissionCompareCaption {
            get {
                return ResourceManager.GetString("PermissionCompareCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been removed from access list..
        /// </summary>
        public static string PermissionRemovedText {
            get {
                return ResourceManager.GetString("PermissionRemovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has same permissions: {1}..
        /// </summary>
        public static string PermissionUnchangedText {
            get {
                return ResourceManager.GetString("PermissionUnchangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string StatusCaption {
            get {
                return ResourceManager.GetString("StatusCaption", resourceCulture);
            }
        }
    }
}
