//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionReportTourResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionReportTourResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.PermissionReportTourResource", typeof(PermissionReportTourResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Access Control List(ACL) can be seen here..
        /// </summary>
        public static string AclOption {
            get {
                return ResourceManager.GetString("AclOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you will see list of all saved reports of folders..
        /// </summary>
        public static string AllSavedReportList {
            get {
                return ResourceManager.GetString("AllSavedReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These folders&apos; ACL differ from the originating folder. Double click on any folder here to start a new scan..
        /// </summary>
        public static string DifferencesOption {
            get {
                return ResourceManager.GetString("DifferencesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can export the report easily by clicking here..
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can select the format of report data to be exported..
        /// </summary>
        public static string ExportWindow {
            get {
                return ResourceManager.GetString("ExportWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can optionally write the path of mapped folder here..
        /// </summary>
        public static string FolderPathTextBox {
            get {
                return ResourceManager.GetString("FolderPathTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand tree, select a folder, and double-click to analyse it. Alternatively, right click on folder, and hit {0}..
        /// </summary>
        public static string FolderTree {
            get {
                return ResourceManager.GetString("FolderTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is owner of the folder..
        /// </summary>
        public static string OwnerOption {
            get {
                return ResourceManager.GetString("OwnerOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to load or delete the report. You can edit the description by clicking on the field..
        /// </summary>
        public static string SavedReportList {
            get {
                return ResourceManager.GetString("SavedReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved reports of this folder can be located here..
        /// </summary>
        public static string SavedReportsOption {
            get {
                return ResourceManager.GetString("SavedReportsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this to save your report in database..
        /// </summary>
        public static string SaveReportButton {
            get {
                return ResourceManager.GetString("SaveReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see all results of this folder..
        /// </summary>
        public static string ScanReport {
            get {
                return ResourceManager.GetString("ScanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dummy Text 2.
        /// </summary>
        public static string ServerNameTextBox {
            get {
                return ResourceManager.GetString("ServerNameTextBox", resourceCulture);
            }
        }
    }
}
