//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.PermissionResource", typeof(PermissionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string ACLAccountNameCaption {
            get {
                return ResourceManager.GetString("ACLAccountNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Control List.
        /// </summary>
        public static string ACLCaption {
            get {
                return ResourceManager.GetString("ACLCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritance Flag.
        /// </summary>
        public static string ACLInheritanceFlagCaption {
            get {
                return ResourceManager.GetString("ACLInheritanceFlagCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited.
        /// </summary>
        public static string ACLInheritedCaption {
            get {
                return ResourceManager.GetString("ACLInheritedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        public static string ACLRightsCaption {
            get {
                return ResourceManager.GetString("ACLRightsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Group Members.
        /// </summary>
        public static string ACLShowMembersCaption {
            get {
                return ResourceManager.GetString("ACLShowMembersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string ACLTypeNameCaption {
            get {
                return ResourceManager.GetString("ACLTypeNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} report is available in database..
        /// </summary>
        public static string AllSavedReportRowCountCaption {
            get {
                return ResourceManager.GetString("AllSavedReportRowCountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reports are available in database..
        /// </summary>
        public static string AllSavedReportRowsCountCaption {
            get {
                return ResourceManager.GetString("AllSavedReportRowsCountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database: Permission Reports.
        /// </summary>
        public static string AllSavedReportsCaption {
            get {
                return ResourceManager.GetString("AllSavedReportsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{0}&quot; - .
        /// </summary>
        public static string AllSavedReportSearchedText {
            get {
                return ResourceManager.GetString("AllSavedReportSearchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} differences found.
        /// </summary>
        public static string DifferencesFoundText {
            get {
                return ResourceManager.GetString("DifferencesFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to generate a Permission Report for each folder listed here? This action may need some time. Do not close the application until it&apos;s finished..
        /// </summary>
        public static string ExportDifferencePermissionReportText {
            get {
                return ResourceManager.GetString("ExportDifferencePermissionReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Inheritance Hierarchy.
        /// </summary>
        public static string GroupInheritanceCaption {
            get {
                return ResourceManager.GetString("GroupInheritanceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shows all groups involved in the inheritance hierarchy.
        ///    
        ///The topmost AD group is the originally authorized group. 
        ///All other groups shown are then nested groups of the above. 
        ///The last group is the group in which the shown user is a member..
        /// </summary>
        public static string GroupInheritanceInfo {
            get {
                return ResourceManager.GetString("GroupInheritanceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate group permissions report..
        /// </summary>
        public static string GroupPermissionsCaption {
            get {
                return ResourceManager.GetString("GroupPermissionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupPermissionsPagesCaption {
            get {
                return ResourceManager.GetString("GroupPermissionsPagesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} groups found..
        /// </summary>
        public static string GroupPermissionsResultsText {
            get {
                return ResourceManager.GetString("GroupPermissionsResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} group found..
        /// </summary>
        public static string GroupPermissionsResultText {
            get {
                return ResourceManager.GetString("GroupPermissionsResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Reports in Database.
        /// </summary>
        public static string MenuShowSavedReportCaption {
            get {
                return ResourceManager.GetString("MenuShowSavedReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than.
        /// </summary>
        public static string MoreThanCaption {
            get {
                return ResourceManager.GetString("MoreThanCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string OwnerCaption {
            get {
                return ResourceManager.GetString("OwnerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Report.
        /// </summary>
        public static string PermissionReportCaption {
            get {
                return ResourceManager.GetString("PermissionReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Users found of: {1}.
        /// </summary>
        public static string PermissionResultsText {
            get {
                return ResourceManager.GetString("PermissionResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} User found of: {1}.
        /// </summary>
        public static string PermissionResultText {
            get {
                return ResourceManager.GetString("PermissionResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports in Database.
        /// </summary>
        public static string PermissionSavedReportCaption {
            get {
                return ResourceManager.GetString("PermissionSavedReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been saved in database..
        /// </summary>
        public static string PermissionSavedText {
            get {
                return ResourceManager.GetString("PermissionSavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{2}&quot; - {0} Users found of: {1}.
        /// </summary>
        public static string PermissionSearchResultsText {
            get {
                return ResourceManager.GetString("PermissionSearchResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{2}&quot; - {0} User found of: {1}.
        /// </summary>
        public static string PermissionSearchResultText {
            get {
                return ResourceManager.GetString("PermissionSearchResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking differences....
        /// </summary>
        public static string ProgressDifferencesText {
            get {
                return ResourceManager.GetString("ProgressDifferencesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ReportDateCaption {
            get {
                return ResourceManager.GetString("ReportDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ReportDescriptionCaption {
            get {
                return ResourceManager.GetString("ReportDescriptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to edit..
        /// </summary>
        public static string ReportDescriptionEditText {
            get {
                return ResourceManager.GetString("ReportDescriptionEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No saved report found..
        /// </summary>
        public static string ReportEmptyCaption {
            get {
                return ResourceManager.GetString("ReportEmptyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string ReportEncryptedCaption {
            get {
                return ResourceManager.GetString("ReportEncryptedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string ReportFolderCaption {
            get {
                return ResourceManager.GetString("ReportFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ReportUserCaption {
            get {
                return ResourceManager.GetString("ReportUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Reports.
        /// </summary>
        public static string SavedReportCompareCaption {
            get {
                return ResourceManager.GetString("SavedReportCompareCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SavedReportDeleteCaption {
            get {
                return ResourceManager.GetString("SavedReportDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Report - {0}.
        /// </summary>
        public static string SavedReportDisplayName {
            get {
                return ResourceManager.GetString("SavedReportDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string SavedReportLoadCaption {
            get {
                return ResourceManager.GetString("SavedReportLoadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Reports.
        /// </summary>
        public static string SavedReportsOfCaption {
            get {
                return ResourceManager.GetString("SavedReportsOfCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Report - {0} ({1}).
        /// </summary>
        public static string SavedReportTitle {
            get {
                return ResourceManager.GetString("SavedReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} row found..
        /// </summary>
        public static string SavedRowCountCaption {
            get {
                return ResourceManager.GetString("SavedRowCountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rows found..
        /// </summary>
        public static string SavedRowsCountCaption {
            get {
                return ResourceManager.GetString("SavedRowsCountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured..
        /// </summary>
        public static string ScanCancelledReasonText {
            get {
                return ResourceManager.GetString("ScanCancelledReasonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Cancelled. {0}.
        /// </summary>
        public static string ScanCancelledText {
            get {
                return ResourceManager.GetString("ScanCancelledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing differences....
        /// </summary>
        public static string StartComparisonCaption {
            get {
                return ResourceManager.GetString("StartComparisonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start permission report..
        /// </summary>
        public static string StartPermissionReportText {
            get {
                return ResourceManager.GetString("StartPermissionReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user found.
        /// </summary>
        public static string UserFoundCaption {
            get {
                return ResourceManager.GetString("UserFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersCaption {
            get {
                return ResourceManager.GetString("UsersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users found.
        /// </summary>
        public static string UsersFoundCaption {
            get {
                return ResourceManager.GetString("UsersFoundCaption", resourceCulture);
            }
        }
    }
}
