//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingReportShareResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingReportShareResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.SettingReportShareResource", typeof(SettingReportShareResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These credentials will be used to impersonate user to run share report without any authentication problem..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed. Invalid user name or password..
        /// </summary>
        public static string InvalidCredentialsText {
            get {
                return ResourceManager.GetString("InvalidCredentialsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordCaption {
            get {
                return ResourceManager.GetString("PasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your windows password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Report.
        /// </summary>
        public static string ShareReportCaption {
            get {
                return ResourceManager.GetString("ShareReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impersonation Account.
        /// </summary>
        public static string UserNameCaption {
            get {
                return ResourceManager.GetString("UserNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username@domain.
        /// </summary>
        public static string UserNamePlaceholder {
            get {
                return ResourceManager.GetString("UserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name must be in &quot;Domain\Name&quot; format..
        /// </summary>
        public static string UserNameValidationText {
            get {
                return ResourceManager.GetString("UserNameValidationText", resourceCulture);
            }
        }
    }
}
