//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedServersResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedServersResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.SharedServersResource", typeof(SharedServersResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        public static string ADBrowserCaption {
            get {
                return ResourceManager.GetString("ADBrowserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name of computer.
        /// </summary>
        public static string ADComputerPlaceholder {
            get {
                return ResourceManager.GetString("ADComputerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add All Servers.
        /// </summary>
        public static string AddAllServersCaption {
            get {
                return ResourceManager.GetString("AddAllServersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        public static string AddServerCaption {
            get {
                return ResourceManager.GetString("AddServerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name of user.
        /// </summary>
        public static string ADUserPlaceholder {
            get {
                return ResourceManager.GetString("ADUserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Connections.
        /// </summary>
        public static string ClientConnectionsCaption {
            get {
                return ResourceManager.GetString("ClientConnectionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The servers file is corrupt or inaccessible..
        /// </summary>
        public static string DataFileLoadError {
            get {
                return ResourceManager.GetString("DataFileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionCaption {
            get {
                return ResourceManager.GetString("DescriptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration Failed. Server not found..
        /// </summary>
        public static string EnumerationFailedCaption {
            get {
                return ResourceManager.GetString("EnumerationFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ListShareNameCaption {
            get {
                return ResourceManager.GetString("ListShareNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Users.
        /// </summary>
        public static string MaxUsersCaption {
            get {
                return ResourceManager.GetString("MaxUsersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} servers.
        /// </summary>
        public static string MoreServersCountCaption {
            get {
                return ResourceManager.GetString("MoreServersCountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewServerCaption {
            get {
                return ResourceManager.GetString("NewServerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0} new).
        /// </summary>
        public static string NewServersCountCaption {
            get {
                return ResourceManager.GetString("NewServersCountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No servers available..
        /// </summary>
        public static string NoServersAvailableCaption {
            get {
                return ResourceManager.GetString("NoServersAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shares available..
        /// </summary>
        public static string NoSharesAvailableCaption {
            get {
                return ResourceManager.GetString("NoSharesAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFS Permission Report.
        /// </summary>
        public static string NtfsReportCaption {
            get {
                return ResourceManager.GetString("NtfsReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} server.
        /// </summary>
        public static string OneServerCountCaption {
            get {
                return ResourceManager.GetString("OneServerCountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PathCaption {
            get {
                return ResourceManager.GetString("PathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFS Permissions Report.
        /// </summary>
        public static string PermissionReportCaption {
            get {
                return ResourceManager.GetString("PermissionReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Servers.
        /// </summary>
        public static string RefreshServersCaption {
            get {
                return ResourceManager.GetString("RefreshServersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all servers.
        /// </summary>
        public static string RemoveAllServersCaption {
            get {
                return ResourceManager.GetString("RemoveAllServersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing all servers. Are you sure?.
        /// </summary>
        public static string RemoveAllServersMessage {
            get {
                return ResourceManager.GetString("RemoveAllServersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string RemoveCaption {
            get {
                return ResourceManager.GetString("RemoveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Server &apos;{0}&apos;. Are you sure?.
        /// </summary>
        public static string RemoveServerMessage {
            get {
                return ResourceManager.GetString("RemoveServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ScanCaption {
            get {
                return ResourceManager.GetString("ScanCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Network.
        /// </summary>
        public static string ScanServerCaption {
            get {
                return ResourceManager.GetString("ScanServerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a share to view details..
        /// </summary>
        public static string SelectShareCaption {
            get {
                return ResourceManager.GetString("SelectShareCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify server name. If there are several servers, you can specify them by comma or semicolon..
        /// </summary>
        public static string ServerNameBoxCaption {
            get {
                return ResourceManager.GetString("ServerNameBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify server name to add..
        /// </summary>
        public static string ServerNameEmptyMessage {
            get {
                return ResourceManager.GetString("ServerNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server has not been scanned..
        /// </summary>
        public static string ServerNotScannedError {
            get {
                return ResourceManager.GetString("ServerNotScannedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string ServersCaption {
            get {
                return ResourceManager.GetString("ServersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These servers already exist in the list - &apos;{0}&apos;..
        /// </summary>
        public static string ServersExistMessage {
            get {
                return ResourceManager.GetString("ServersExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} server(s) found..
        /// </summary>
        public static string ServersFoundMessage {
            get {
                return ResourceManager.GetString("ServersFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Name.
        /// </summary>
        public static string ShareNameCaption {
            get {
                return ResourceManager.GetString("ShareNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected share is removed from server, or the server is unavailable at the moment..
        /// </summary>
        public static string ShareNotFoundError {
            get {
                return ResourceManager.GetString("ShareNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustees.
        /// </summary>
        public static string TrusteesCaption {
            get {
                return ResourceManager.GetString("TrusteesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or group was not found in Active Directory..
        /// </summary>
        public static string UserOrGroupNotFound {
            get {
                return ResourceManager.GetString("UserOrGroupNotFound", resourceCulture);
            }
        }
    }
}
