//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.TemplateResource", typeof(TemplateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove selected templates?.
        /// </summary>
        public static string AskRemovetAllText {
            get {
                return ResourceManager.GetString("AskRemovetAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove &apos;{0}&apos; template?.
        /// </summary>
        public static string AskRemovetText {
            get {
                return ResourceManager.GetString("AskRemovetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected template.
        /// </summary>
        public static string EditTemplateText {
            get {
                return ResourceManager.GetString("EditTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template.
        /// </summary>
        public static string EditTemplateTitle {
            get {
                return ResourceManager.GetString("EditTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameCaption {
            get {
                return ResourceManager.GetString("NameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New template.
        /// </summary>
        public static string NewTemplateText {
            get {
                return ResourceManager.GetString("NewTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Template.
        /// </summary>
        public static string NewTemplateTitle {
            get {
                return ResourceManager.GetString("NewTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolderTip {
            get {
                return ResourceManager.GetString("OpenFolderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PathCaption {
            get {
                return ResourceManager.GetString("PathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected template.
        /// </summary>
        public static string RemoveTemplateText {
            get {
                return ResourceManager.GetString("RemoveTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Owner Report.
        /// </summary>
        public static string StartOwnerReportText {
            get {
                return ResourceManager.GetString("StartOwnerReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Permission Report.
        /// </summary>
        public static string StartPermissionReportText {
            get {
                return ResourceManager.GetString("StartPermissionReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Report.
        /// </summary>
        public static string StartReportTip {
            get {
                return ResourceManager.GetString("StartReportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start User Report.
        /// </summary>
        public static string StartUserReportText {
            get {
                return ResourceManager.GetString("StartUserReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file &apos;{0}&apos; is corrupt..
        /// </summary>
        public static string TemplateFileCorruptError {
            get {
                return ResourceManager.GetString("TemplateFileCorruptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template List empty. Click.
        /// </summary>
        public static string TemplateListEmptyPartOne {
            get {
                return ResourceManager.GetString("TemplateListEmptyPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to add new item..
        /// </summary>
        public static string TemplateListEmptyPartTwo {
            get {
                return ResourceManager.GetString("TemplateListEmptyPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserCaption {
            get {
                return ResourceManager.GetString("UserCaption", resourceCulture);
            }
        }
    }
}
