//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TourResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TourResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.TourResource", typeof(TourResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Report Tour.
        /// </summary>
        public static string FolderReportTourCaption {
            get {
                return ResourceManager.GetString("FolderReportTourCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides you on how you generate folder reports..
        /// </summary>
        public static string FolderReportTourDescription {
            get {
                return ResourceManager.GetString("FolderReportTourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Report Tour.
        /// </summary>
        public static string OwnerReportTourCaption {
            get {
                return ResourceManager.GetString("OwnerReportTourCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides you on how to select an AD User and checks what folders are owned by this account..
        /// </summary>
        public static string OwnerReportTourDescription {
            get {
                return ResourceManager.GetString("OwnerReportTourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Report Tour.
        /// </summary>
        public static string PermissionReportTourCaption {
            get {
                return ResourceManager.GetString("PermissionReportTourCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides you on how to analyze NTFS permissions and to report them..
        /// </summary>
        public static string PermissionReportTourDescription {
            get {
                return ResourceManager.GetString("PermissionReportTourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Report Tour.
        /// </summary>
        public static string ShareReportTourCaption {
            get {
                return ResourceManager.GetString("ShareReportTourCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides you on how to enumerate servers in your network and gathers all share informations..
        /// </summary>
        public static string ShareReportTourDescription {
            get {
                return ResourceManager.GetString("ShareReportTourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the tour at startup..
        /// </summary>
        public static string ShowTourAtStartCaption {
            get {
                return ResourceManager.GetString("ShowTourAtStartCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartTourCaption {
            get {
                return ResourceManager.GetString("StartTourCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to learn using FolderSecurityViewer?.
        /// </summary>
        public static string StartUpQuestionText {
            get {
                return ResourceManager.GetString("StartUpQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Tour.
        /// </summary>
        public static string TakeTourCaption {
            get {
                return ResourceManager.GetString("TakeTourCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TourOptionsCloseCaption {
            get {
                return ResourceManager.GetString("TourOptionsCloseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permissions Report Tour.
        /// </summary>
        public static string UserReportTourCaption {
            get {
                return ResourceManager.GetString("UserReportTourCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides you on how to analyze user, and its permission on folders, and sub folders..
        /// </summary>
        public static string UserReportTourDescription {
            get {
                return ResourceManager.GetString("UserReportTourDescription", resourceCulture);
            }
        }
    }
}
