//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV.Resources.UserReportResource", typeof(UserReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} report is available in database..
        /// </summary>
        public static string AllSavedReportResultCaption {
            get {
                return ResourceManager.GetString("AllSavedReportResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reports are available in database..
        /// </summary>
        public static string AllSavedReportResultsCaption {
            get {
                return ResourceManager.GetString("AllSavedReportResultsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database: User Permission Reports.
        /// </summary>
        public static string AllSavedReportsCaption {
            get {
                return ResourceManager.GetString("AllSavedReportsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{1}&quot; - {0} report is available in database..
        /// </summary>
        public static string AllSavedReportSearchResultCaption {
            get {
                return ResourceManager.GetString("AllSavedReportSearchResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{1}&quot; - {0} reports are available in database..
        /// </summary>
        public static string AllSavedReportSearchResultsCaption {
            get {
                return ResourceManager.GetString("AllSavedReportSearchResultsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select two reports with same folder path and user..
        /// </summary>
        public static string CompareDifferentReportsText {
            get {
                return ResourceManager.GetString("CompareDifferentReportsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare reports of {0} and {1} of user {2}..
        /// </summary>
        public static string CompareReportCaption {
            get {
                return ResourceManager.GetString("CompareReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Report.
        /// </summary>
        public static string CompareReportDisplayName {
            get {
                return ResourceManager.GetString("CompareReportDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Report - {0} in {1}.
        /// </summary>
        public static string CompareReportTitle {
            get {
                return ResourceManager.GetString("CompareReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders found in: {1}.
        /// </summary>
        public static string FolderResultsText {
            get {
                return ResourceManager.GetString("FolderResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folder found in: {1}.
        /// </summary>
        public static string FolderResultText {
            get {
                return ResourceManager.GetString("FolderResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{2}&quot; - {0} folders found in: {1}.
        /// </summary>
        public static string FolderSearchResultsText {
            get {
                return ResourceManager.GetString("FolderSearchResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{2}&quot; - {0} folder found in: {1}.
        /// </summary>
        public static string FolderSearchResultText {
            get {
                return ResourceManager.GetString("FolderSearchResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder found.
        /// </summary>
        public static string LoadFolderCaption {
            get {
                return ResourceManager.GetString("LoadFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folders found.
        /// </summary>
        public static string LoadFoldersCaption {
            get {
                return ResourceManager.GetString("LoadFoldersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of selected reports were not removed. Check log file for more details..
        /// </summary>
        public static string NotAllDeletedMessage {
            get {
                return ResourceManager.GetString("NotAllDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reports found in database..
        /// </summary>
        public static string ReportEmptyCaption {
            get {
                return ResourceManager.GetString("ReportEmptyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permissions Report saved in database..
        /// </summary>
        public static string ReportSaved {
            get {
                return ResourceManager.GetString("ReportSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SavedDateCaption {
            get {
                return ResourceManager.GetString("SavedDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SavedDescriptionCaption {
            get {
                return ResourceManager.GetString("SavedDescriptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string SavedFolderCaption {
            get {
                return ResourceManager.GetString("SavedFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated By.
        /// </summary>
        public static string SavedGeneratedByCaption {
            get {
                return ResourceManager.GetString("SavedGeneratedByCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Report - {1} ({0}).
        /// </summary>
        public static string SavedReportDisplayName {
            get {
                return ResourceManager.GetString("SavedReportDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string SavedReportDomainCaption {
            get {
                return ResourceManager.GetString("SavedReportDomainCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Name.
        /// </summary>
        public static string SavedReportNameCaption {
            get {
                return ResourceManager.GetString("SavedReportNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originating Group.
        /// </summary>
        public static string SavedReportOriginatingGroupCaption {
            get {
                return ResourceManager.GetString("SavedReportOriginatingGroupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string SavedReportPermissionsCaption {
            get {
                return ResourceManager.GetString("SavedReportPermissionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} row found..
        /// </summary>
        public static string SavedReportResultCaption {
            get {
                return ResourceManager.GetString("SavedReportResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rows found..
        /// </summary>
        public static string SavedReportResultsCaption {
            get {
                return ResourceManager.GetString("SavedReportResultsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{1}&quot; - {0} row found..
        /// </summary>
        public static string SavedReportSearchResultCaption {
            get {
                return ResourceManager.GetString("SavedReportSearchResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched &quot;{1}&quot; - {0} rows found..
        /// </summary>
        public static string SavedReportSearchResultsCaption {
            get {
                return ResourceManager.GetString("SavedReportSearchResultsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Folder.
        /// </summary>
        public static string SavedReportSubFolderCaption {
            get {
                return ResourceManager.GetString("SavedReportSubFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Report - {2} in {1} ({0}).
        /// </summary>
        public static string SavedReportTitle {
            get {
                return ResourceManager.GetString("SavedReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string SavedUserCaption {
            get {
                return ResourceManager.GetString("SavedUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permissions Report.
        /// </summary>
        public static string UserReportCaption {
            get {
                return ResourceManager.GetString("UserReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string UserReportFolderCaption {
            get {
                return ResourceManager.GetString("UserReportFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1}.
        /// </summary>
        public static string UserReportHeaderCaption {
            get {
                return ResourceManager.GetString("UserReportHeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Name.
        /// </summary>
        public static string UserReportNameCaption {
            get {
                return ResourceManager.GetString("UserReportNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folders skipped during scan..
        /// </summary>
        public static string ZeroSkippedFoldersText {
            get {
                return ResourceManager.GetString("ZeroSkippedFoldersText", resourceCulture);
            }
        }
    }
}
